/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package city_planning.pnl;

import city_planning.achievements.Dlg_achievements;
import city_planning.assets.Dlg_assets;
import city_planning.barangay_officials.Dlg_barangay_officials;
import city_planning.barangays.Barangays;
import city_planning.barangays.Dlg_barangays;
import city_planning.basic_needs.Dlg_basic_needs;
import city_planning.bathroom_types.Dlg_bathroom_types;
import city_planning.blood_types.Dlg_blood_types;
import city_planning.building_types.Dlg_building_types;
import city_planning.businesses.Dlg_businesses;
import city_planning.certifications.Dlg_certifications;
import city_planning.cities.Dlg_cities;
import city_planning.citizenships.Dlg_citizenships;
import city_planning.clearances.Dlg_clearance;

import city_planning.communication_types.Dlg_communication;
import city_planning.compartments.Dlg_compartments;
import city_planning.cooking_lighting_types.Dlg_cooking_lightning_types;
import city_planning.disabilities.Dlg_disabilities;
import city_planning.disposal_methods.Dlg_disposal_methods;
import city_planning.dlg.Dlg_search;

import city_planning.educational_statuses.Dlg_educational_status;
import city_planning.floor_types.Dlg_floor_types;
import city_planning.genders.Dlg_genders;
import city_planning.kitchen_types.Dlg_kitchen_types;
import static city_planning.pnl.MyMain.getSerialNumber;
import city_planning.professions.Dlg_professions;
import city_planning.provinces.Dlg_provinces;
import city_planning.puroks.Dlg_puroks;
import city_planning.regions.Dlg_regions;
import city_planning.religions.Dlg_religions;
import city_planning.reports.Dlg_report_barangay_clearances;
import city_planning.reports.Dlg_survey_form;
import city_planning.roof_types.Dlg_roof_types;
import city_planning.schools.Dlg_schools;
import city_planning.settings.Dlg_settings;
import city_planning.skills.Dlg_skills;
import city_planning.solid_waste_disposal_methods.Dlg_solid_waste_disposal_methods;
import city_planning.streets.Dlg_streets;
import city_planning.toilet_types.Dlg_toilet_types;
import city_planning.util.Alert;
import city_planning.util.DeEncrypter;
import city_planning.util.Dlg_get_hdd_serial;
import city_planning.util.MyFrame;
import city_planning.wall_types.Dlg_wall_types;
import city_planning.tranportation_types.Dlg_transportation_types;
import city_planning.users.Dlg_users;
import city_planning.users.MyUser;
import city_planning.users.Users;
import city_planning.water_sources.Dlg_water_sources;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.*;
import mijzcx.synapse.desk.utils.Application;
import mijzcx.synapse.desk.utils.CloseDialog;

import synsoftech.fields.Button;
import synsoftech.fields.Field;

/**
 *
 * @author i1
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Pnl_Dashboard
     */
    public Dashboard() {
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnl_main_holder = new javax.swing.JPanel();
        pnl_login = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tf_username = new Field.Input();
        jLabel12 = new javax.swing.JLabel();
        tf_password = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new Button.Default();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JDesktopPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(185, 106, 154));

        jLabel51.setBackground(new java.awt.Color(234, 234, 234));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/city_planning/img_city_planning/menu53.png"))); // NOI18N
        jLabel51.setOpaque(true);
        jLabel51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel51MouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("V.0.20160310");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setBackground(new java.awt.Color(185, 106, 154));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });

        pnl_main_holder.setBackground(new java.awt.Color(204, 204, 204));
        pnl_main_holder.setLayout(new java.awt.CardLayout());

        pnl_login.setBackground(new java.awt.Color(255, 255, 255));

        login.setOpaque(false);

        jLabel8.setBackground(new java.awt.Color(185, 106, 154));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(185, 106, 154));
        jLabel8.setText("Username:");

        tf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usernameActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(185, 106, 154));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(185, 106, 154));
        jLabel12.setText("Password:");

        tf_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_passwordActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(185, 106, 154));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(185, 106, 154));
        jLabel13.setText("Login with your ");

        jLabel14.setBackground(new java.awt.Color(185, 106, 154));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(185, 106, 154));
        jLabel14.setText("credentials!");

        jButton2.setForeground(new java.awt.Color(185, 106, 154));
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/city_planning/img_menu/city_planning.png"))); // NOI18N

        jLabel15.setBackground(new java.awt.Color(185, 106, 154));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(185, 106, 154));
        jLabel15.setText("Profiling");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(185, 106, 154));
        jLabel3.setText("Synapse Software Technologies");

        jLabel4.setForeground(new java.awt.Color(185, 106, 154));
        jLabel4.setText("Integrating Business with Technology");

        jLabel5.setForeground(new java.awt.Color(185, 106, 154));
        jLabel5.setText("Developed by:");

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_username)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_password)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4)))
                .addGap(5, 5, 5)
                .addComponent(jLabel13)
                .addGap(1, 1, 1)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(1, 1, 1)
                .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel12)
                .addGap(1, 1, 1)
                .addComponent(tf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_loginLayout = new javax.swing.GroupLayout(pnl_login);
        pnl_login.setLayout(pnl_loginLayout);
        pnl_loginLayout.setHorizontalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_loginLayout.setVerticalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_loginLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(1, 1, 1)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_main_holder.add(pnl_login, "card5");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        pnl_main_holder.add(jPanel1, "card2");

        jPanel6.setBackground(new java.awt.Color(216, 137, 184));

        jLabel10.setBackground(new java.awt.Color(185, 106, 154));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/city_planning/img_menu_transactions/maximize.png"))); // NOI18N
        jLabel10.setToolTipText("Inventory Adjuster");
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(185, 106, 154));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/city_planning/img_menu_transactions/purchase1.png"))); // NOI18N
        jLabel16.setToolTipText("Receipts");
        jLabel16.setOpaque(true);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnl_main_holder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl_main_holder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosing

    private void tf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usernameActionPerformed

        tf_password.grabFocus();
    }//GEN-LAST:event_tf_usernameActionPerformed

    private void tf_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_passwordActionPerformed
        login();

    }//GEN-LAST:event_tf_passwordActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        if (jPanel6.isVisible()) {
            jPanel6.setVisible(false);
        } else {
            jPanel6.setVisible(true);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel51MouseClicked
        menu();
    }//GEN-LAST:event_jLabel51MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        login();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered

    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked

    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered

    }//GEN-LAST:event_jLabel16MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Application.setSystemLookAndFeel();
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                Dashboard aw = new Dashboard();
                Toolkit tk = Toolkit.getDefaultToolkit();
                int xSize = ((int) tk.getScreenSize().
                        getWidth());
                int ySize = ((int) tk.getScreenSize().
                        getHeight());
                aw.setSize(xSize, ySize);
                Dimension d = aw.jPanel1.getSize();
                aw.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JDesktopPane jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel login;
    private javax.swing.JPanel pnl_login;
    private javax.swing.JPanel pnl_main_holder;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables

    private void myInit() {
        key();
        ret_default_location();
        set_card_items();
        jPanel6.setVisible(false);
    }

    String my_region = "";
    String my_region_id = "";
    String my_province = "";
    String my_province_id = "";
    String my_city = "";
    String my_city_id = "";
    String my_barangay = "";
    String my_barangay_id = "";
    String my_purok = "";
    String my_purok_id = "";

    private void ret_default_location() {

        String where = " where is_default=1";
        List<Barangays.to_barangays> datas = Barangays.ret_data(where);
        Barangays.to_barangays location = datas.get(0);
        my_region = location.region;
        my_region_id = "" + location.region_id;
        my_province = location.province;
        my_province_id = "" + location.province_id;
        my_city = location.city;
        my_city_id = "" + location.city_id;
        my_barangay = location.barangay;
        my_barangay_id = "" + location.id;

        MyUser.setRegion(my_region);
        MyUser.setRegion_id(my_region_id);
        MyUser.setProvince(my_province);
        MyUser.setProvince_id(my_province_id);
        MyUser.setCity(my_city);
        MyUser.setCity_id(my_city_id);
        MyUser.setBarangay(my_barangay);
        MyUser.setBarangay_id(my_barangay_id);
    }
    int count = 0;

    private void key() {
        tf_username.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {

                if (e.getKeyCode() == KeyEvent.VK_F10) {
                    if (count == 2) {
                        license_code();
                        count = 0;
                    }
                    count++;
                }
            }
        });
    }

    private void license_code() {
        Window p = (Window) this;
        Dlg_get_hdd_serial nd = Dlg_get_hdd_serial.create(p, true);
        nd.setTitle("");
        nd.setCallback(new Dlg_get_hdd_serial.Callback() {

            @Override
            public void ok(CloseDialog closeDialog, Dlg_get_hdd_serial.OutputData data) {
                closeDialog.ok();

            }
        });
        nd.setLocationRelativeTo(this);
        nd.setVisible(true);
    }

    CardLayout cardLayout = new CardLayout();

    private void set_card_items() {
        cardLayout = (CardLayout) pnl_main_holder.getLayout();

        cardLayout.addLayoutComponent("1", pnl_login);
        cardLayout.addLayoutComponent("2", jPanel1);

    }

    private void hover() {
        JLabel[] lbl = {};
        for (final JLabel l : lbl) {
            l.setVisible(false);
            l.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent e) {
                    if (l.isEnabled()) {
                        l.setBackground(new java.awt.Color(255, 255, 255));
                    }

                }

                @Override
                public void mouseExited(MouseEvent e) {
                    if (l.isEnabled()) {
                        l.setBackground(new java.awt.Color(140, 175, 227));
                    }
                }
            });
        }
    }

    public JDesktopPane pane() {
        return jPanel1;

    }

    private void dlg_same_size() {
//        Dlg_users dtc = new Dlg_users();
//        MyFrame.set2(dtc.getSurface(), jPanel1, "Users");
    }

    private void dlg_maximize() {
        Dlg_search rpt = new Dlg_search();
        MyFrame.set(rpt.getSurface(), jPanel1, "City Planning");
    }

    private void menu() {

        Window p = (Window) this;
        Dlg_menu nd = Dlg_menu.create(p, true);
        nd.setTitle("");
        nd.setCallback(new Dlg_menu.Callback() {

            @Override
            public void minimize(CloseDialog closeDialog, Dlg_menu.OutputData data) {
                closeDialog.ok();
                Dashboard.this.setState(Frame.ICONIFIED);
            }

            @Override
            public void ok1(CloseDialog closeDialog, Dlg_menu.OutputData data) {
                closeDialog.ok();

                if (data.stmt.equals("standby")) {
                    JLabel[] lbl = {jLabel10, jLabel16};
                    for (final JLabel l : lbl) {
                        l.setVisible(false);
                    }
                    jPanel6.setVisible(false);
                    cardLayout.show(pnl_main_holder, "1");

                }

                if (data.stmt.equals("logout")) {
                    System.exit(1);
                }
                if (data.stmt.equals("minimize")) {
                    Dashboard.this.setState(Frame.ICONIFIED);
                }

                //<editor-fold defaultstate="collapsed" desc=" transactions ">
                if (data.stmt.equals("Profiles")) {
                    transactions_profiles();
                }

                if (data.stmt.equals("Clearances")) {
                    transactions_clearances();
                }

                //</editor-fold>
                //<editor-fold defaultstate="collapsed" desc=" maintenance ">
                if (data.stmt.equals("Achievements")) {
                    maintenance_achievements();
                }
                if (data.stmt.equals("Assets")) {
                    maintenance_assets();
                }
                if (data.stmt.equals("Barangays")) {
                    maintenance_barangays();
                }
                if (data.stmt.equals("Basic Needs")) {
                    maintenance_basic_needs();
                }
                if (data.stmt.equals("Bathroom Types")) {
                    maintenance_bathroom_types();
                }
                if (data.stmt.equals("Blood Types")) {
                    maintenance_blood_types();
                }
                if (data.stmt.equals("Building Types")) {
                    maintenance_building_types();
                }
                if (data.stmt.equals("Certifications")) {
                    maintenance_certifications();
                }
                if (data.stmt.equals("Cities")) {
                    maintenance_cities();
                }
                if (data.stmt.equals("Citizenships")) {
                    maintenance_citizenships();
                }

                if (data.stmt.equals("Communication Types")) {
                    maintenance_communication();
                }
                if (data.stmt.equals("Compartments")) {
                    maintenance_compartments();
                }
                if (data.stmt.equals("Cooking Lightning Types")) {
                    maintenance_cooking_lighting_types();
                }
                if (data.stmt.equals("Disabilities")) {
                    maintenance_disabilities();
                }
                if (data.stmt.equals("Disposal Methods")) {
                    maintenance_disposal_methods();
                }
                if (data.stmt.equals("Educational Statuses")) {
                    maintenance_educational_status();
                }
                if (data.stmt.equals("Floor Types")) {
                    maintenance_floor_types();
                }
                if (data.stmt.equals("Kitchen Types")) {
                    maintenance_kitchen();
                }
                if (data.stmt.equals("Professions")) {
                    maintenance_professions();
                }
                if (data.stmt.equals("Provinces")) {
                    maintenance_provinces();
                }
                if (data.stmt.equals("Puroks")) {
                    maintenance_puroks();
                }
                if (data.stmt.equals("Regions")) {
                    maintenance_regions();
                }
                if (data.stmt.equals("Religions")) {
                    maintenance_religions();
                }
                if (data.stmt.equals("Roof Types")) {
                    maintenance_roof_types();
                }
                if (data.stmt.equals("Schools")) {
                    maintenance_school();
                }

                if (data.stmt.equals("Skills")) {
                    maintenance_skills();
                }
                if (data.stmt.equals("Solid Waste Disposal Methods")) {
                    maintenance_solid_waste_disposal_methods();
                }
                if (data.stmt.equals("Streets")) {
                    maintenance_streets();
                }
                if (data.stmt.equals("Toilet Types")) {
                    maintenance_toilet_types();
                }
                if (data.stmt.equals("Transportation Types")) {
                    maintenance_transportation_available();
                }

                if (data.stmt.equals("Users")) {
                    maintenance_users();
                }
                if (data.stmt.equals("Wall Types")) {
                    maintenance_wall_types();
                }
                if (data.stmt.equals("Water Sources")) {
                    maintenance_water_sources();
                }
                if (data.stmt.equals("Barangay Officials")) {
                    maintenance_barangay_officials();
                }
                if (data.stmt.equals("Settings")) {
                    maintenance_settings();
                }

                //</editor-fold>
                //<editor-fold defaultstate="collapsed" desc=" Reports ">
                if (data.stmt.equals("Barangay Clearances")) {
                    report_barangay_clearances();
                }
                if (data.stmt.equals("Survey Form")) {
                    report_survey_form();
                }
                //</editor-fold>
            }

            @Override
            public void standby(CloseDialog closeDialog, Dlg_menu.OutputData data) {

                closeDialog.ok();
            }

            @Override
            public void logout(CloseDialog closeDialog, Dlg_menu.OutputData data) {
                closeDialog.ok();
            }
        });
        Point point = jLabel51.getLocationOnScreen();
        nd.setLocation(point.x - 125, point.y + 37);
        nd.setVisible(true);
    }

    private void login() {
        String license_code = System.getProperty("license_code", "");
        String hdd_license = DeEncrypter.encrypt(getSerialNumber());

        if (!license_code.equals(hdd_license)) {
            Alert.set(0, "Invalid license key, please register!");
            return;
        }
        String user_name = tf_username.getText();
        String password = tf_password.getText();
        if (user_name.isEmpty() || password.isEmpty()) {
            Alert.set(0, "Field must not be empty!");
            tf_username.grabFocus();
            return;
        }
        password = DeEncrypter.encrypt(password);
        String where = " ";
        List<Users.to_users> datas = Users.ret_data(where);
        int exist = 0;
        for (Users.to_users user : datas) {
            String my_user = user.user_name;
            String my_password = user.password;
            if (my_user.equals(user_name) && my_password.equals(password) && user.barangay_id.equals(my_barangay_id)) {
                MyUser.setUser_id("" + user.id);
                MyUser.setUser_name(user.user_name);
                MyUser.setUser_screen_name(user.screen_name);
                exist = 1;
                break;
            }
        }
        if (exist == 1) {
            tf_username.setText("");
            tf_password.setText("");
            jPanel1.removeAll();
            jPanel1.updateUI();
            cardLayout.show(pnl_main_holder, "2");

        } else {
            Alert.set(0, "Username/password did not matched!");
            tf_username.grabFocus();
        }

    }
    //<editor-fold defaultstate="collapsed" desc=" transaction functions ">

    private void transactions_profiles() {

        Dlg_search dtc = new Dlg_search();
        MyFrame.set(dtc.getSurface(), jPanel1, "Search");
    }

    private void transactions_clearances() {

        Dlg_clearance dtc = new Dlg_clearance();
        MyFrame.set(dtc.getSurface(), jPanel1, "Search");
    }

//</editor-fold>
    //<editor-fold defaultstate="collapsed" desc=" maintenance functions ">
    private void maintenance_assets() {

        Dlg_assets dtc = new Dlg_assets();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Assets", dtc.getWidth(), dtc.getHeight());

    }

    private void maintenance_achievements() {

        Dlg_achievements dtc = new Dlg_achievements();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Achievements", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_barangays() {

        Dlg_barangays dtc = new Dlg_barangays();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Barangays", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_basic_needs() {

        Dlg_basic_needs dtc = new Dlg_basic_needs();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Basic Needs", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_blood() {

        Dlg_blood_types dtc = new Dlg_blood_types();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Blood", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_businesses() {

        Dlg_businesses dtc = new Dlg_businesses();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Business", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_communication() {

        Dlg_communication dtc = new Dlg_communication();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Communication", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_compartments() {

        Dlg_compartments dtc = new Dlg_compartments();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Compartments", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_cooking_lighting_types() {

        Dlg_cooking_lightning_types dtc = new Dlg_cooking_lightning_types();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Cooking Lighting Types", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_disabilities() {

        Dlg_disabilities dtc = new Dlg_disabilities();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Disabilities", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_disposal_methods() {

        Dlg_disposal_methods dtc = new Dlg_disposal_methods();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Disposal Methods", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_certifications() {

        Dlg_certifications dtc = new Dlg_certifications();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Certifications", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_cities() {

        Dlg_cities dtc = new Dlg_cities();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Cities", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_citizenships() {

        Dlg_citizenships dtc = new Dlg_citizenships();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Citizenships", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_bathroom_types() {

        Dlg_bathroom_types dtc = new Dlg_bathroom_types();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Bathroom", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_blood_types() {

        Dlg_blood_types dtc = new Dlg_blood_types();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Blood", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_building_types() {

        Dlg_building_types dtc = new Dlg_building_types();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Building", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_kitchen() {

        Dlg_kitchen_types dtc = new Dlg_kitchen_types();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Kitchen", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_professions() {

        Dlg_professions dtc = new Dlg_professions();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Professions", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_provinces() {

        Dlg_provinces dtc = new Dlg_provinces();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Provinces", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_puroks() {

        Dlg_puroks dtc = new Dlg_puroks();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Puroks", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_regions() {

        Dlg_regions dtc = new Dlg_regions();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Regions", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_religions() {

        Dlg_religions dtc = new Dlg_religions();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Religions", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_genders() {

        Dlg_genders dtc = new Dlg_genders();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Genders", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_educational_status() {

        Dlg_educational_status dtc = new Dlg_educational_status();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Education", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_floor_types() {

        Dlg_floor_types dtc = new Dlg_floor_types();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Floor Types", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_skills() {

        Dlg_skills dtc = new Dlg_skills();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Skills", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_solid_waste_disposal_methods() {

        Dlg_solid_waste_disposal_methods dtc = new Dlg_solid_waste_disposal_methods();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Solid Waste Disposal Methods", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_streets() {

        Dlg_streets dtc = new Dlg_streets();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Streets", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_transportation_available() {

        Dlg_transportation_types dtc = new Dlg_transportation_types();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Transportation", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_users() {

        Dlg_users dtc = new Dlg_users();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Users", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_roof_types() {

        Dlg_roof_types dtc = new Dlg_roof_types();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Roof", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_wall_types() {

        Dlg_wall_types dtc = new Dlg_wall_types();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Wall", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_water_sources() {

        Dlg_water_sources dtc = new Dlg_water_sources();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Water Sources", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_toilet_types() {

        Dlg_toilet_types dtc = new Dlg_toilet_types();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Toilet", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_school() {

        Dlg_schools dtc = new Dlg_schools();
        MyFrame.set2(dtc.getSurface(), jPanel1, "School", dtc.getWidth(), dtc.getHeight());
    }

    private void maintenance_barangay_officials() {

        Dlg_barangay_officials dtc = new Dlg_barangay_officials();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Barangay Officials", dtc.getWidth(), dtc.getHeight());

    }

    private void maintenance_settings() {

        Dlg_settings dtc = new Dlg_settings();
        MyFrame.set2(dtc.getSurface(), jPanel1, "Settings", dtc.getWidth(), dtc.getHeight());

    }

    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc=" Reports ">
    private void report_barangay_clearances() {
        Dlg_report_barangay_clearances dtc = new Dlg_report_barangay_clearances();

        MyFrame.set(dtc.getSurface(), jPanel1, "Barangay Clearances");
    }

    private void report_survey_form() {
        Dlg_survey_form dtc = new Dlg_survey_form();

        MyFrame.set(dtc.getSurface(), jPanel1, "Survey Form");
    }
    //</editor-fold>
}
