--
-- Definition of table `streets`
--
--Please cooperate-
DROP TABLE IF EXISTS `streets`;
CREATE TABLE `streets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `street` varchar(100) DEFAULT NULL,
  `purok_id` int(11) DEFAULT NULL,
  `purok` varchar(100) DEFAULT NULL,
  `barangay_id` int(11) DEFAULT NULL,
  `barangay` varchar(100) DEFAULT NULL,
  `city_id` int(11) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `province_id` int(11) DEFAULT NULL,
  `province` varchar(100) DEFAULT NULL,
  `region_id` int(11) DEFAULT NULL,
  `region` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=102 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `streets`
--


--
-- Definition of table `puroks`
--
DROP TABLE IF EXISTS `puroks`;
CREATE TABLE `puroks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `purok` varchar(100) DEFAULT NULL,
  `barangay_id` int(11) DEFAULT NULL,
  `barangay` varchar(100) DEFAULT NULL,
  `city_id` int(11) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `province_id` int(11) DEFAULT NULL,
  `province` varchar(100) DEFAULT NULL,
  `region_id` int(11) DEFAULT NULL,
  `region` varchar(100) DEFAULT NULL,
  `street` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;




INSERT INTO `puroks` (`id`,`purok`,`barangay_id`,`barangay`, `city_id`,`city`, `province_id`, `province`, `region_id`, `region`,`is_default`) VALUES 
(1, 'Purok 1',207, 'Barangay 7 (Mangga)','471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',1),
(2, 'Purok 2',207, 'Barangay 7 (Mangga)','471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',1),
(3, 'Purok 3',207, 'Barangay 7 (Mangga)','471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',1),
(4, 'Purok 4',207, 'Barangay 7 (Mangga)','471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',1),
(5, 'Purok 5',207, 'Barangay 7 (Mangga)','471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',1),
(6, 'Purok 6',207, 'Barangay 7 (Mangga)','471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',1),
(7, 'Purok 7',207, 'Barangay 7 (Mangga)','471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',1);

--
-- Dumping data for table `puroks`
--

--
-- Definition of table `barangay`
--

DROP TABLE IF EXISTS `barangays`;
CREATE TABLE `barangays` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `barangay` varchar(100) DEFAULT NULL,
  `purok_id` int(11) DEFAULT NULL,
  `purok` varchar(100) DEFAULT NULL,
  `city_id` int(11) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `province_id` int(11) DEFAULT NULL,
  `province` varchar(100) DEFAULT NULL,
  `region_id` int(11) DEFAULT NULL,
  `region` varchar(100) DEFAULT NULL,
  `is_default` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=332 DEFAULT CHARSET=latin1;


INSERT INTO `barangays` (`id`,`barangay`,`city_id`,`city`, `province_id`, `province`, `region_id`, `region`,`is_default`) VALUES 
(1, 'Bio-os','462', 'Amlan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(2, 'Jantianon','462', 'Amlan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(3, 'Jugno','462', 'Amlan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(4, 'Mag-abo','462', 'Amlan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(5, 'Poblacion','462', 'Amlan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(6, 'Silab','462', 'Amlan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(7, 'Tambojangin','462', 'Amlan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(8, 'Tandayag','462', 'Amlan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0);
INSERT INTO `barangays` (`id`,`barangay`,`city_id`,`city`, `province_id`, `province`, `region_id`, `region`,`is_default`) VALUES
(9, 'Ambus','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(10, 'Anibong','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(11, 'Atabay','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(12, 'Awa-an','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(13, 'Ban-ban','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(14, 'Calagcalag','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(15, 'Candana-ay','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(16, 'Carol-an','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(17, 'Gomentoc','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(18, 'Inacban','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(19, 'Iniban','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(20, 'Jandalamanon','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(21, 'Kilaban','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(22, 'Lamigan','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(23, 'Maaslum','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(24, 'Mabato','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(25, 'Manogtong','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(26, 'Nabhang','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(27, 'Poblacion','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(28, 'Tambo','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(29, 'Tampocon I','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(30, 'Tampocon II','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(31, 'Tibyawan','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(32, 'Tiguib','463', 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0);
INSERT INTO `barangays` (`id`,`barangay`,`city_id`,`city`, `province_id`, `province`, `region_id`, `region`,`is_default`) VALUES
(213, 'Balayagmanok','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(214, 'Banilad','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(33, 'Buntis','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(34, 'Buntod','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(35, 'Calangag','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(36, 'Combado','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(37, 'Doldol','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(38, 'Isugan','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(39, 'Liptong','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(40, 'Lutao','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(41, 'Magsuot','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(42, 'Malabago','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(43, 'Mampas','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(44, 'North Poblacion','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(45, 'Sacsac','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(46, 'San Miguel','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(47, 'South Poblacion','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(48, 'Sulodpan','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(49, 'Timbanga','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(50, 'Timbao','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(51, 'Tubod','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(52, 'West Poblacion','464', 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0);
INSERT INTO `barangays` (`id`,`barangay`,`city_id`,`city`, `province_id`, `province`, `region_id`, `region`,`is_default`) VALUES
(53, 'Barangay I (Pob.)', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(54, 'Barangay II (Pob.)', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(55, 'Basak', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(56, 'Biñohon', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(57, 'Cabanlutan', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(58, 'Calasga-an', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(59, 'Cambagahan', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(60, 'Cambaguio', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(61, 'Cambanjao', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(62, 'Cambuilao', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(63, 'Canlargo', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(64, 'Capiñahan', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(65, 'Consolacion', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(66, 'Dansulan', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(67, 'Hangyad', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(68, 'La Paz', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(69, 'Lo-oc', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(70, 'Lonoy', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(71, 'Mabunao', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(72, 'Manlipac', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(73, 'Mansangaban', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(74, 'Okiot', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(75, 'Olympia', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(76, 'Panala-an', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(77, 'Panam-angan', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(78, 'Rosario', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(79, 'Sab-ahan', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(80, 'San Isidro', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(81, 'Katacgahan (Tacgahan)', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(82, 'Tagpo', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(83, 'Talungon', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(84, 'Tamisu', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(85, 'Tamogong', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(86, 'Tangculogan', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(87, 'Valencia', '465', 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0);
INSERT INTO `barangays` (`id`,`barangay`,`city_id`,`city`, `province_id`, `province`, `region_id`, `region`,`is_default`) VALUES
(88, 'Actin', '466', 'Basay','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(89, 'Bal-os', '466', 'Basay','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(90, 'Bongalonan', '466', 'Basay','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(91, 'Cabalayongan', '466', 'Basay','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(92, 'Cabatuanan', '466', 'Basay','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(93, 'Linantayan', '466', 'Basay','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(94, 'Maglinao', '466', 'Basay','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(95, 'Nagbo-alao', '466', 'Basay','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(96, 'Olandao', '466', 'Basay','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(97, 'Poblacion', '466', 'Basay','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0);
INSERT INTO `barangays` (`id`,`barangay`,`city_id`,`city`, `province_id`, `province`, `region_id`, `region`,`is_default`) VALUES
(98, 'Ali-is', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(99, 'Banaybanay', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(100, 'Banga', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(101, 'Villasol (Bato)', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(102, 'Boyco (Poblacion)', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(103, 'Bugay', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(104, 'Cansumalig', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(105, 'Dawis', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(106, 'Kalamtukan', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(107, 'Kalumboyan', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(108, 'Malabugas', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(109, 'Mandu-ao', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(110, 'Maninihon', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(111, 'Minaba', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(112, 'Nangka', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(113, 'Narra', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(114, 'Pagatban', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(115, 'San Jose', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(116, 'San Miguel', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(117, 'San Roque', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(118, 'Suba (poblacion)', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(119, 'Tabuan', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(120, 'Tayawan', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(121, 'Tinago (poblacion)', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(122, 'Ubos (poblacion)', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(123, 'Villareal', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(124, 'San Isidro', '467', 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0);
INSERT INTO `barangays` (`id`,`barangay`,`city_id`,`city`, `province_id`, `province`, `region_id`, `region`,`is_default`) VALUES
(125, 'Atotes', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(126, 'Batangan', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(127, 'Bulod', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(128, 'Cabcaban', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(129, 'Cabugan', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(130, 'Camudlas', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(131, 'Canluto', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(132, 'Danao', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(133, 'Danawan', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(134, 'Domolog', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(135, 'Malaga', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(136, 'Manseje', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(137, 'Matobato', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(138, 'Nagcasunog', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(139, 'Nalundan', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(140, 'Pangalaycayan', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(141, 'Peñahan', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(142, 'Poblacion (Payabon)', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(143, 'Salong', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(144, 'Tagaytay', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(145, 'Tinaogan', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(146, 'Tubod', '468', 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0);
INSERT INTO `barangays` (`id`,`barangay`,`city_id`,`city`, `province_id`, `province`, `region_id`, `region`,`is_default`) VALUES
(147, 'Bayog', '469', 'Canlaon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(148, 'Binalbagan', '469', 'Canlaon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(149, 'Bucalan (East Budlasan)', '469', 'Canlaon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(150, 'Linothangan', '469', 'Canlaon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(151, 'Lumapao', '469', 'Canlaon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(152, 'Malaiba', '469', 'Canlaon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(153, 'Masulog', '469', 'Canlaon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(154, 'Panubigan', '469', 'Canlaon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(155, 'Mabigo (Poblacion - Canla-on City)', '469', 'Canlaon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(156, 'Pula', '469', 'Canlaon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(157, 'Budlasan (West Budlasan)', '469', 'Canlaon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(158, 'Aquino', '469', 'Canlaon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0);
INSERT INTO `barangays` (`id`,`barangay`,`city_id`,`city`, `province_id`, `province`, `region_id`, `region`,`is_default`) VALUES
(159, 'Apo Island', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(160, 'Anhawan', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(161, 'Bagacay', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(162, 'Baslay', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(163, 'Batuhon Dacu', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(164, 'Batuhon Dacu', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(165, 'Boloc-boloc', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(166, 'Bulak', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(167, 'Bunga', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(168, 'Casile', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(169, 'Libjo', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(170, 'Lipayo', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(171, 'Maayongtubig', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(172, 'Mag-aso', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(173, 'Magsaysay', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(174, 'Malongcay Dacu', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(175, 'Masaplod Norte', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(176, 'Masaplod Sur', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(177, 'Panubtuban', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(178, 'Panubtuban', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(179, 'Poblacion II', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(180, 'Poblacion III', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(181, 'Tugawe', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(182, 'Tunga-tunga', '470', 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0);
INSERT INTO `barangays` (`id`,`barangay`,`city_id`,`city`, `province_id`, `province`, `region_id`, `region`,`is_default`) VALUES
(183, 'Bagacay', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(184, 'Bajumpandan', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(185, 'Balugo', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(186, 'Banilad', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(187, 'Bantayan', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(188, 'Batinguel', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(189, 'Buñao', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(190, 'Cadawinonan', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(191, 'Calindagan', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(192, 'Camanjac', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(193, 'Candau-ay', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(194, 'Cantil-e', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(195, 'Daro', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(196, 'Junob', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(197, 'Looc', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(198, 'Mangnao-Canal', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(199, 'Motong', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(200, 'Piapi', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(201, 'Barangay 1 (Tinago)', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(202, 'Barangay 2 (Upper Lukewright)', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(203, 'Barangay 3 (Business District))', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(204, 'Barangay 4 (Rizal Boulevard)', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(205, 'Barangay 5 (Silliman Area)', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(206, 'Barangay 6 (Cambagroy)', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(207, 'Barangay 7 (Mangga)', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(208, 'Barangay 8 (Cervantes Extension)', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(209, 'Pulantubig', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(210, 'Tabuc-tubig', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(211, 'Taclobo', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0),
(212, 'Talay', '471', 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)',0);



--
-- Dumping data for table `barangay`
--

--
-- Definition of table `cities`
--

DROP TABLE IF EXISTS `cities`;
CREATE TABLE `cities` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `city` varchar(100) DEFAULT NULL,
  `province_id` int(11) DEFAULT NULL,
  `province` varchar(100) DEFAULT NULL,
  `region_id` int(11) DEFAULT NULL,
  `region` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=143 DEFAULT CHARSET=latin1;


INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES 
 (1, 'Adam','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (2, 'Bacarra','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (3, 'Badoc','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (4, 'Bangui','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (5, 'Banna(Espiritu)','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (6, 'Batac','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (7, 'Burgos','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (8, 'Carasi','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (9, 'Currimao','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (10, 'Dingras','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (11, 'Dumalneg','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (12, 'Laoag','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (13, 'Marcos','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (14, 'Nueva Era','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (15, 'Pagudpud','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (16, 'Paoay','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (17, 'Pasuquin','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (18, 'Piddig','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (19, 'Pinili','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (20, 'San Nicolas','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (21, 'Sarrat','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (22, 'Solsona','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)'),
 (23, 'Vintar','6','Ilocos Norte Province','2','Luzon REGION I (Ilocos Region)');
INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES 
 (24, 'Alilem','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (25, 'Banayoyo','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (26, 'Bantay','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (27, 'Burgos','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (28, 'Cabugao','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'), 
 (29, 'Candon','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (30, 'Caoayan','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (31, 'Cervantes','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (32, 'Galimuyod','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (33, 'gregorio Del Pilar','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (34, 'Lidlidda','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (35, 'Magsingal','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (36, 'Nagbukel','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (37, 'Narvacan','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (38, 'Quirino','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (39, 'Salcedo','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (40, 'San Emilio','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (41, 'San Esteban','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (42, 'San Eldefonso','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (43, 'San Juan','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (44, 'San Vicente','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (45, 'Santa','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (46, 'Santa Catalina','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (47, 'Santa Cruz','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (48, 'Santa Lucia','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (49, 'Santa MAria','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (50, 'Santiago','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (51, 'Santo Dimingo','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (52, 'Sigay','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (53, 'Sinait','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (54, 'Sugpon','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (55, 'Suyo','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (56, 'Tagudin','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)'),
 (57, 'Vigan','7','Ilocos Sur Province','2','Luzon REGION I (Ilocos Region)');
INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
 (58, 'Agoo','8','La Union Province','2','Luzon REGION I (Ilocos Region)'),
 (59, 'Aringay','8','La Union Province','2','Luzon REGION I (Ilocos Region)'),
 (60, 'Bacnotan','8','La Union Province','2','Luzon REGION I (Ilocos Region)'),
 (61, 'Bagulin','8','La Union Province','2','Luzon REGION I (Ilocos Region)'),
 (62, 'Balaoan','8','La Union Province','2','Luzon REGION I (Ilocos Region)'),
 (63, 'Bangar','8','La Union Province','2','Luzon REGION I (Ilocos Region)'),
 (64, 'Bauang','8','La Union Province','2','Luzon REGION I (Ilocos Region)'),
 (65, 'Burgos','8','La Union Province','2','Luzon REGION I (Ilocos Region)'),
 (66, 'Caba','8','La Union Province','2','Luzon REGION I (Ilocos Region)'),
 (67, 'Luna','8','La Union Province','2','Luzon REGION I (Ilocos Region)'),
 (68, 'Naguilian','8','La Union Province','2','Luzon REGION I (Ilocos Region)'),
 (69, 'Pugo','8','La Union Province','2','Luzon REGION I (Ilocos Region)'),
 (70, 'Rosario','8','La Union Province','2','Luzon REGION I (Ilocos Region)'),
 (71, 'San Fernando','8','La Union Province','2','Luzon REGION I (Ilocos Region)'),
 (72, 'San Gabriel','8','La Union Province','2','Luzon REGION I (Ilocos Region)'),
 (73, 'San Juan','8','La Union Province','2','Luzon REGION I (Ilocos Region)'),
 (74, 'Santo Tomas','8','La Union Province','2','Luzon REGION I (Ilocos Region)'),
 (75, 'Santol','8','La Union Province','2','Luzon REGION I (Ilocos Region)'),
 (76, 'Sudipen','8','La Union Province','2','Luzon REGION I (Ilocos Region)'),
 (77, 'Tubao','8','La Union Province','2','Luzon REGION I (Ilocos Region)');
INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(78, 'Agno','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(79, 'Aguilar','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(80, 'Alaminos','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(81, 'Alcala','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(82, 'Anda','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(83, 'Asingan','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(84, 'Balungao','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(85, 'Bani','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(86, 'Basista','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(87, 'Bautista','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(88, 'Bayambang','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(89, 'Binalonan','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(100, 'Binmaley','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(101, 'Bolinao','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(102, 'Bugallon','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(103, 'Burgos','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(104, 'Calasiao','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(105, 'Dagupan','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(106, 'Dasol','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(107, 'Infanta','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(108, 'Labrador','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(109, 'Laoac','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(110, 'Lingayen','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(111, 'Mabini','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(112, 'Malasiqui','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(113, 'Manaoag','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(114, 'Mangaldan','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(115, 'Mangatarem','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(116, 'Mapandan','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(117, 'Natividad','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(118, 'Pozorrubio','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(119, 'Rosales','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(120, 'San Carlos','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(121, 'San Fabian','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(122, 'San Jacinto','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(123, 'San Manuel','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(124, 'San Nicolas','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(125, 'San Quintin','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(126, 'Santa Barbara','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(127, 'Santa Maria','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(128, 'Santo Tomas','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(129, 'Sison','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(130, 'Sual','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(131, 'Tayug','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(132, 'Umingan','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(133, 'Urbiztondo','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(134, 'Urbaneta','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)'),
(135, 'Villasis','9','Pangasinan Province','2','Luzon REGION I (Ilocos Region)');
INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(136, 'Basco','10','Batanes Province','3','Luzon REGION II (Cagayan Valley)'),
(137, 'Itbayat','10','Batanes Province','3','Luzon REGION II (Cagayan Valley)'),
(138, 'Ivana','10','Batanes Province','3','Luzon REGION II (Cagayan Valley)'),
(139, 'Mahatao','10','Batanes Province','3','Luzon REGION II (Cagayan Valley)'),
(140, 'Sabtang','10','Batanes Province','3','Luzon REGION II (Cagayan Valley)'),
(141, 'Uyugan','10','Batanes Province','3','Luzon REGION II (Cagayan Valley)'),
(142, 'Abulug','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(143, 'Alcala','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(144, 'Allacapan','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(145, 'Amulung','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(146, 'Appari','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(147, 'Baggao','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(148, 'Ballesteros','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(149, 'Buguey','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(150, 'Calayan','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(151, 'Camalaniugan','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(152, 'Claveria','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(153, 'Enrile','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(154, 'Gattaran','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(155, 'Gonzaga','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(156, 'Iguig','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(157, 'Lal-Lo','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(158, 'Lasam','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(159, 'Pamplona','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(160, 'Peñablanca','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(161, 'Piat','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(162, 'Rizal','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(163, 'Sanchez-Mira','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(164, 'Santa Ana','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(165, 'Santa Praxedes','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(166, 'Santa Teresita','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(167, 'Santo Niño','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(168, 'Solana','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(169, 'Tuao','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)'),
(170, 'Tuguegarao','11','Cagayan Province','3','Luzon REGION II (Cagayan Valley)');
INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(171, 'Alicia','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(172, 'Angadana','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(173, 'Aurora','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(174, 'Benito','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(175, 'Soliven','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(176, 'Burgos','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(177, 'Cabagan','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(178, 'Cabatuan','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(179, 'Cauayan','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(180, 'Cordon','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(181, 'Delfin ALbano','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(182, 'Dinapigue','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(183, 'Divilacan','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(184, 'Echague','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(185, 'Gamu','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(186, 'Jones','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(187, 'Ilagan','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(188, 'Luna ','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(189, 'Macanacon','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(190, 'Mallig','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(191, 'Naguilian ','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(192, 'Palanan ','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(193, 'Quezon','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(194, 'Quirino','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(195, 'Ramon','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(196, 'Reinan Mercedes','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(197, 'Roxas','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(198, 'San Agustin','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(199, 'San Guillermo','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(200, 'San Isidro','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(201, 'San Manuel','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(202, 'San Mariano','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(203, 'San Mateo','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(204, 'San Pablo','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(205, 'Santa Maria','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(206, 'Santo Tomas','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)'),
(207, 'Tumauini','12','Isabela Province','3','Luzon REGION II (Cagayan Valley)');
INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(208, 'Alfonso Castañeda','13','Nueva Vizcaya Province','3','Luzon REGION II (Cagayan Valley)'),
(209, 'Ambaguio','13','Nueva Vizcaya Province','3','Luzon REGION II (Cagayan Valley)'),
(210, 'Aritao','13','Nueva Vizcaya Province','3','Luzon REGION II (Cagayan Valley)'),
(211, 'Bagabag','13','Nueva Vizcaya Province','3','Luzon REGION II (Cagayan Valley)'),
(212, 'Bambang','13','Nueva Vizcaya Province','3','Luzon REGION II (Cagayan Valley)'),
(213, 'Bayombong','13','Nueva Vizcaya Province','3','Luzon REGION II (Cagayan Valley)'),
(214, 'Diadi','13','Nueva Vizcaya Province','3','Luzon REGION II (Cagayan Valley)'),
(215, 'Dupax del Norte','13','Nueva Vizcaya Province','3','Luzon REGION II (Cagayan Valley)'),
(216, 'Dupax del Sur','13','Nueva Vizcaya Province','3','Luzon REGION II (Cagayan Valley)'),
(217, 'Kasibu','13','Nueva Vizcaya Province','3','Luzon REGION II (Cagayan Valley)'),
(218, 'Kayapa','13','Nueva Vizcaya Province','3','Luzon REGION II (Cagayan Valley)'),
(219, 'Quezon','13','Nueva Vizcaya Province','3','Luzon REGION II (Cagayan Valley)'),
(220, 'Santa Fe','13','Nueva Vizcaya Province','3','Luzon REGION II (Cagayan Valley)'),
(221, 'Solano','13','Nueva Vizcaya Province','3','Luzon REGION II (Cagayan Valley)'),
(222, 'Villaverde','13','Nueva Vizcaya Province','3','Luzon REGION II (Cagayan Valley)');
INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(223, 'Aglipay','14','Quirino Province','3','Luzon REGION II (Cagayan Valley)'),
(224, 'Cabarraguis','14','Quirino Province','3','Luzon REGION II (Cagayan Valley)'),
(225, 'Diffun','14','Quirino Province','3','Luzon REGION II (Cagayan Valley)'),
(226, 'Maddela','14','Quirino Province','3','Luzon REGION II (Cagayan Valley)'),
(227, 'Nagtipuna','14','Quirino Province','3','Luzon REGION II (Cagayan Valley)'),
(228, 'Saguday','14','Quirino Province','3','Luzon REGION II (Cagayan Valley)');
INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(229, 'Altavas','38','Aklan Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(230, 'Balete','38','Aklan Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(231, 'Banga','38','Aklan Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(232, 'Batan','38','Aklan Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(233, 'Buruanga','38','Aklan Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(234, 'Ibajay','38','Aklan Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(235, 'Kalibo','38','Aklan Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(236, 'Lezo','38','Aklan Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(237, 'Libacao','38','Aklan Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(238, 'Madalag','38','Aklan Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(239, 'Makato','38','Aklan Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(240, 'Malay','38','Aklan Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(241, 'Malinao','38','Aklan Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(242, 'Nabas','38','Aklan Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(243, 'New Washington','38','Aklan Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(244, 'Numancia','38','Aklan Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(245, 'Tangalan','38','Aklan Province','8','VISAYAS REGION VI (WESTERN VISAYAS)');
INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(246, 'Anini-y','39','Antique Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(247, 'Barbaza','39','Antique Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(248, 'Belison','39','Antique Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(249, 'Bugasong','39','Antique Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(250, 'Caluya','39','Antique Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(251, 'Culasi','39','Antique Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(252, 'Hamtic','39','Antique Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(253, 'Laua-an','39','Antique Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(254, 'Libertad','39','Antique Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(255, 'Pandan','39','Antique Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(256, 'Patnongon','39','Antique Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(257, 'San Jose de Buenavista','39','Antique Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(258, 'San Remigio','39','Antique Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(259, 'Sebaste','39','Antique Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(260, 'Sibalom','39','Antique Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(261, 'Tibiao','39','Antique Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(262, 'Tobias Fornier','39','Antique Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(263, 'Valderrama','39','Antique Province','8','VISAYAS REGION VI (WESTERN VISAYAS)');
INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(264, 'Cuartero','40','Capiz Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(265, 'Dao','40','Capiz Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(266, 'Dumalag','40','Capiz Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(267, 'Dumarao','40','Capiz Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(268, 'Ivisan','40','Capiz Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(269, 'Jamindan','40','Capiz Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(270, 'Maayon','40','Capiz Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(271, 'Mambusao','40','Capiz Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(272, 'Panay','40','Capiz Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(273, 'Panitan','40','Capiz Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(274, 'Pilar','40','Capiz Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(275, 'Pontevedra','40','Capiz Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(276, 'President Roxas','40','Capiz Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(277, 'Roxas City','40','Capiz Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(278, 'Sapian','40','Capiz Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(279, 'Sigma','40','Capiz Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(280, 'Tapaz','40','Capiz Province','8','VISAYAS REGION VI (WESTERN VISAYAS)');
INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(281, 'Ajuy','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(282, 'Alimodian','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(283, 'Anilao','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(284, 'Badiangan','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(285, 'Balasan','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(286, 'Banate','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(287, 'Barotac Nuevo','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(288, 'Barotac Viejo','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(289, 'Batad','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(290, 'Bingawan','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(291, 'Cabatuan','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(292, 'Calinog','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(293, 'Carles','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(294, 'Conception','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(295, 'Dingle','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(296, 'Dueñas','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(297, 'Dumangas','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(298, 'Estancia','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(299, 'Guimbal','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(300, 'Igbaras','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(301, 'Iloilo City','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(302, 'Janiuay','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(303, 'Lambunao','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(304, 'Leganes','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(305, 'Lemery','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(306, 'Leon','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(307, 'Maasin','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(308, 'Miagao','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(309, 'Mina','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(310, 'New Lucena','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(311, 'Oton','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(312, 'Passi','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(313, 'Pavia','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(314, 'Pototan','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(315, 'San Dionisio','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(316, 'San Enrique','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(317, 'San Joaquin','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(318, 'San Miguel','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(319, 'San Rafael','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(320, 'Santa Barabara','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(321, 'Sara','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(322, 'Tigbauan','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(323, 'Tubungan','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(324, 'Zarraga','41','Iloilo Province','8','VISAYAS REGION VI (WESTERN VISAYAS)');
INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(325, 'Buenavista','42','Guimaras Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(326, 'Jordan','42','Guimaras Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(327, 'Nueva Valencia','42','Guimaras Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(328, 'San Lorenzo','42','Guimaras Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(329, 'Sibunag','42','Guimaras Province','8','VISAYAS REGION VI (WESTERN VISAYAS)');
INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(330, 'Bacolod','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(331, 'Bago','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(332, 'Binalbagan','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(333, 'Cadiz','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(334, 'Calatrava','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(335, 'Candoni','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(336, 'Cauayan','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(337, 'Enrique B. Magalona','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(338, 'Escalante','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(339, 'Himamaylan','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(340, 'Hinigaran','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(341, 'Hinoba-an','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(342, 'Ilog','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(343, 'Isabela','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(344, 'Kabankalan','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(345, 'La Carlota','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(346, 'La Castellana','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(347, 'Manapla','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(348, 'Moises Padilla','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(349, 'Murcia','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(350, 'Pontevedra','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(351, 'Pulunpandan','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(352, 'Sagay','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(353, 'Salavador Benedicto','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(354, 'San Carlos','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(355, 'San Enrique','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(356, 'Silay','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(357, 'Sipalay','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(358, 'Talisay','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(359, 'Toboso','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(360, 'Valladolid','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)'),
(361, 'Victorias','43','Negros Occidental Province','8','VISAYAS REGION VI (WESTERN VISAYAS)');
INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(362, 'Alburquerque','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(363, 'Alicia','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(364, 'Anda','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(3651, 'Anteque','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(3661, 'Baclayon','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(3662, 'Baliliyan','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(3652, 'Batuan','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(3663, 'Bien Unido','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(367, 'Bilar','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(368, 'Buenavista','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(369, 'Calape','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(370, 'Candijay','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(371, 'Carmen','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(372, 'Catigbian','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(373, 'Clarin','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(374, 'Corella','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(375, 'Cortes','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(376, 'Dagohoy','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(377, 'Danao','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(378, 'Dauis','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(379, 'Dimiao','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(380, 'Duero','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(381, 'Garcia Hernandez','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(382, 'Getafe','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(383, 'Guindulman','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(384, 'Inabanga','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(385, 'Jagna','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(386, 'Lila','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(387, 'Loay','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(388, 'Loboc','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(389, 'Loon','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(390, 'Mabini','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(391, 'Maribojoc','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(392, 'Panglao','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(393, 'Pilar','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(394, 'President Carlos P. Garcia','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(395, 'Sagbayan','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(396, 'San Isidro','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(397, 'San Miguel','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(398, 'Sevilla','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(399, 'Sierra','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(400, 'Sierra Bullones','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(401, 'Sikatuna','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(402, 'Tagbilaran','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(403, 'Talibon','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(404, 'Trinidad','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(405, 'Tubigon','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(406, 'Ubay','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(407, 'Valencia','44','Bohol Province','9','VISAYAS REGION VI (WESTERN VISAYAS)');
INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(408, 'Alcantara','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(409, 'Alcoy','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(410, 'Alegria','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(411, 'Aloguinsan','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(412, 'Argao','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(413, 'Asturias','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(414, 'Badian','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(415, 'Balamban','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(416, 'Bantayan','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(417, 'Barili','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(418, 'Bogo','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(419, 'Boljoon','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(420, 'Borbon','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(421, 'Carcar','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(422, 'Carmen','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(423, 'Catmon','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(424, 'Cebu City','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(425, 'Compostela','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(426, 'Consolacion','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(427, 'Cordova','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(428, 'Daanbantayan','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(429, 'Dalaguete','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(430, 'Danao','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(431, 'Dumanjug','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(432, 'Ginatilan','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(433, 'Lapu-Lapu','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(434, 'Liloan','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(435, 'Madridejos','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(436, 'Nagtipuna','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(437, 'Malabuyoc','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(438, 'Mandaue','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(439, 'Madellin','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(440, 'Minglanilla','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(441, 'Moalboal','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(442, 'Naga','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(443, 'Oslob','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(444, 'Pilar','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(445, 'Pinamungajan','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(446, 'Poro','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(447, 'Ronda','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(448, 'Samboan','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(449, 'San Fernando','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(450, 'San Francisco','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(451, 'San Remigio','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(452, 'Santa Fe','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(453, 'Santander','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(454, 'Sibonga','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(455, 'Sogod','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(456, 'Tabogon','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(457, 'Tabuelan','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(458, 'Talisay','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(459, 'Toledo','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(460, 'Tuburan','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(461, 'Tudela','45','Cebu Province','9','VISAYAS REGION VI (WESTERN VISAYAS)');
INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(462, 'Amlan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(463, 'Ayungon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(464, 'Bacong','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(465, 'Bais','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(466, 'Basay','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(467, 'Bayawan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(468, 'Bindoy','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(469, 'Canlaon','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(470, 'Dauin','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(471, 'Dumaguete','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(472, 'Guihulngan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(473, 'Jimalalud','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(474, 'La Libertad','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(475, 'Mabinay','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(476, 'Manjuyod','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(477, 'Pamplona','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(478, 'San Jose','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(479, 'Santa Catalina','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(480, 'Siaton','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(481, 'Sibulan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(482, 'Tanjay','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(483, 'Tayasan','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(484, 'Valencia','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(485, 'Vallerhermoso','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(486, 'Zamboanguita','46','Negros Oriental Province','9','VISAYAS REGION VI (WESTERN VISAYAS)');
INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(487, 'Enrique Villanueva','47','Siquijor Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(489, 'Larena','47','Siquijor Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(490, 'Lazi','47','Siquijor Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(491, 'Maria','47','Siquijor Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(492, 'San Juan','47','Siquijor Province','9','VISAYAS REGION VI (WESTERN VISAYAS)'),
(493, 'Siquijor','47','Siquijor Province','9','VISAYAS REGION VI (WESTERN VISAYAS)');
INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(494, 'Ameria','48','Biliran Province','10','VISAYAS REGION VI (WESTERN VISAYAS)'),
(495, 'Biliran','48','Biliran Province','10','VISAYAS REGION VI (WESTERN VISAYAS)'),
(496, 'Cabucgayan','48','Biliran Province','10','VISAYAS REGION VI (WESTERN VISAYAS)'),
(497, 'Caibiran','48','Biliran Province','10','VISAYAS REGION VI (WESTERN VISAYAS)'),
(498, 'Culaba','48','Biliran Province','10','VISAYAS REGION VI (WESTERN VISAYAS)'),
(499, 'Kawayan','48','Biliran Province','10','VISAYAS REGION VI (WESTERN VISAYAS)'),
(500, 'Maripipi','48','Biliran Province','10','VISAYAS REGION VI (WESTERN VISAYAS)'),
(501, 'Naval','48','Biliran Province','10','VISAYAS REGION VI (WESTERN VISAYAS)');



INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(502, 'Nagtipuna','49','Eastern Samar Province','10','VISAYAS REGION VI (WESTERN VISAYAS)');

INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(503, 'Nagtipuna','50','Leyte Province','10','VISAYAS REGION VI (WESTERN VISAYAS)');

INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(504, 'Nagtipuna','51','Northern Samar Province','10','VISAYAS REGION VI (WESTERN VISAYAS)');

INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(505, 'Nagtipuna','52','Samar (Western) Province','10','VISAYAS REGION VI (WESTERN VISAYAS)');

INSERT INTO `cities` (`id`,`city`,`province_id`,`province`, `region_id`, `region`) VALUES
(506, 'Nagtipuna','53','Southern Leyte Province','10','VISAYAS REGION VI (WESTERN VISAYAS)');



--
-- Dumping data for table `cities`
--


--
-- Definition of table `provinces`
--

DROP TABLE IF EXISTS `provinces`;
CREATE TABLE `provinces` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `province` varchar(100) DEFAULT NULL,
  `region_id` int(11) DEFAULT NULL,
  `region` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=83 DEFAULT CHARSET=latin1;

INSERT INTO `provinces` (`id`,`region`,`region_id`,`province`) VALUES 
 (6,'Luzon REGION I (Ilocos Region)','2','Ilocos Norte Province'),
 (7,'Luzon REGION I (Ilocos Region)','2','Ilocos Sur Province'),
 (8,'Luzon REGION I (Ilocos Region)','2','La Union Province'),
 (9,'Luzon REGION I (Ilocos Region)','2','Pangasinan Province'),
 (10,'Luzon REGION II (Cagayan Valley)','3','Batanes Province'),
 (11,'Luzon REGION II (Cagayan Valley)','3','Cagayan Province'),
 (12,'Luzon REGION II (Cagayan Valley)','3','Isabela Province'),
 (13,'Luzon REGION II (Cagayan Valley)','3','Nueva Vizcaya Province'),
 (14,'Luzon REGION II (Cagayan Valley)','3','Quirino Province'),
 (15,'Luzon REGION III (Central Luzon)','4','Aurora Province'),
 (16,'Luzon REGION III (Central Luzon)','4','Bataan Province'),
 (17,'Luzon REGION III (Central Luzon)','4','Bulacan Province'),
 (18,'Luzon REGION III (Central Luzon)','4','Nueva Ecija Province'),
 (19,'Luzon REGION III (Central Luzon)','4','Pampanga Province'),
 (20,'Luzon REGION III (Central Luzon)','4','Tarlac Province'),
 (21,'Luzon REGION III (Central Luzon)','4','Zambales Province');
INSERT INTO `provinces` (`id`,`region`,`region_id`,`province`) VALUES 
 (22,'Luzon REGION IV-A (CALABARZON)','5','Batangas Province'),
 (23,'Luzon REGION IV-A (CALABARZON)','5','Cavite Province'),
 (24,'Luzon REGION IV-A (CALABARZON)','5','Laguna Province'),
 (25,'Luzon REGION IV-A (CALABARZON)','5','Quezon Province'),
 (26,'Luzon REGION IV-A (CALABARZON)','5','Rizal Province'),
 (27,'REGION IV-B (MIMAROPA)','6','Marinduque Province'),
 (28,'REGION IV-B (MIMAROPA)','6','Mindoro Occidental Province'),
 (29,'REGION IV-B (MIMAROPA)','6','Mindoro Oriental Province'),
 (30,'REGION IV-B (MIMAROPA)','6','Palawan Province'),
 (31,'REGION IV-B (MIMAROPA)','6','Romblon Province');
INSERT INTO `provinces` (`id`,`region`,`region_id`,`province`) VALUES 
 (32,'Luzon REGION V (BICOL Region)','7','Albay Province'),
 (33,'Luzon REGION V (BICOL Region)','7','Camarines Norte Province'),
 (34,'Luzon REGION V (BICOL Region)','7','Camarines Sur Province'),
 (35,'Luzon REGION V (BICOL Region)','7','Catanduanes Province'),
 (36,'Luzon REGION V (BICOL Region)','7','Masbate Province'),
 (37,'Luzon REGION V (BICOL Region)','7','Sorsogon Province'),
 (38,'VISAYAS REGION VI (WESTERN VISAYAS)','8','Aklan Province'),
 (39,'VISAYAS REGION VI (WESTERN VISAYAS)','8','Antique Province'),
 (40,'VISAYAS REGION VI (WESTERN VISAYAS)','8','Capiz Province'),
 (41,'VISAYAS REGION VI (WESTERN VISAYAS)','8','Iloilo Province'),
 (42,'VISAYAS REGION VI (WESTERN VISAYAS)','8','Guimaras Province'),
 (43,'VISAYAS REGION VI (WESTERN VISAYAS)','8','Negros Occidental Province'),
 (44,'VISAYAS REGION VII (CENTRAL VISAYAS)','9','Bohol Province'),
 (45,'VISAYAS REGION VII (CENTRAL VISAYAS)','9','Cebu Province'),
 (46,'VISAYAS REGION VII (CENTRAL VISAYAS)','9','Negros Oriental Province'),
 (47,'VISAYAS REGION VII (CENTRAL VISAYAS)','9','Siquijor Province'),
 (48,'VISAYAS REGION VIII (EASTERN VISAYAS)','10','Biliran Province'),
 (49,'VISAYAS REGION VIII (EASTERN VISAYAS)','10','Eastern Samar Province'),
 (50,'VISAYAS REGION VIII (EASTERN VISAYAS)','10','Leyte Province'),
 (51,'VISAYAS REGION VIII (EASTERN VISAYAS)','10','Northern Samar Province'),
 (52,'VISAYAS REGION VIII (EASTERN VISAYAS)','10','Samar (Western) Province'),
 (53,'VISAYAS REGION VIII (EASTERN VISAYAS)','10','Southern Leyte Province');
INSERT INTO `provinces` (`id`,`region`,`region_id`,`province`) VALUES 
 (54,'MINDANAO REGION IX (Zamboanga Peninsula)',11,'Zamboanga Sibugay Province'),
 (55,'MINDANAO REGION IX (Zamboanga Peninsula)',11,'Zamboanga del Norte Province'),
 (56,'MINDANAO REGION IX (Zamboanga Peninsula)',11,'Zamboanga del Sur Province'),
 (57,'MINDANAO REGION X (Northern Mindanao)',12,'Bukidnon Province'),
 (58,'MINDANAO REGION X (Northern Mindanao)',12,'Camiguin Province'),
 (59,'MINDANAO REGION X (Northern Mindanao)',12,'Misamis Occidental Province'),
 (60,'MINDANAO REGION X (Northern Mindanao)',12,'Msamis Oriental Province'),
 (61,'MINDANAO REGION X (Northern Mindanao)',12,'Lanao del Norte Province'),
 (62,'MINDANAO REGION XI (Davao Region)',13,'Davao del Norte Province'),
 (63,'MINDANAO REGION XI (Davao Region)',13,'Davao del Sur Province'),
 (64,'MINDANAO REGION XI (Davao Region)',13,'Davao Oriental Province'),
 (65,'MINDANAO REGION XI (Davao Region)',13,'Comostela Valley Province'),
 (66,'MINDANAO REGION XII (Soccsksargen Region)',14,'North Cotabato Province'),
 (67,'MINDANAO REGION XII (Soccsksargen Region)',14,'Sultan Kudarat Province'),
 (68,'MINDANAO REGION XII (Soccsksargen Region)',14,'South Cotabato Province'),
 (69,'MINDANAO REGION XII (Soccsksargen Region)',14,'Saranggani Province'),
 (70,'MINDANAO REGION XIII (Caraga Region)',15,'Agustan del Norte Province'),
 (71,'MINDANAO REGION XIII (Caraga Region)',15,'Augustan del Sur Province'),
 (72,'MINDANAO REGION XIII (Caraga Region)',15,'Suriago del Norte Province'),
 (73,'MINDANAO REGION XIII (Caraga Region)',15,'Suriago del Sur Province');
INSERT INTO `provinces` (`id`,`region`,`region_id`,`province`) VALUES 
 (74,'LUZON REGION XIV (Cordillera Administrative Region (CAR) Region)',16,'Abra Province'),
 (75,'LUZON REGION XIV (Cordillera Administrative Region (CAR) Region)',16,'Benguet Province'),
 (76,'LUZON REGION XIV (Cordillera Administrative Region (CAR) Region)',16,'Ifuga Province'),
 (77,'LUZON REGION XIV (Cordillera Administrative Region (CAR) Region)',16,'Kalinga Province'),
 (78,'LUZON REGION XIV (Cordillera Administrative Region (CAR) Region)',16,'Apayao Province'),
 (79,'LUZON REGION XIV (Cordillera Administrative Region (CAR) Region)',16,'Mountain Province'),
 (80,'MINDANAO REGION XV (Autonomous Region of Muslim Mindanao (ARMM) Region)',17,'Basilan Province'),
 (81,'MINDANAO REGION XV (Autonomous Region of Muslim Mindanao (ARMM) Region)',17,'Sulu Province'),
 (82,'MINDANAO REGION XV (Autonomous Region of Muslim Mindanao (ARMM) Region)',17,'Tawi-Tawi Province'),
 (83,'MINDANAO REGION XV (Autonomous Region of Muslim Mindanao (ARMM) Region)',17,'Lanao del Sur Province'),
 (84,'MINDANAO REGION XV (Autonomous Region of Muslim Mindanao (ARMM) Region)',17,'Magrindanao Province'),
 (85,'Luzon REGION XVI (National Capital Region (NCR) Region)',18,'Manila (composed of the cities within Manila)');
 
/*!40000 ALTER TABLE `provinces` ENABLE KEYS */;

--
-- Dumping data for table `provinces`
--

--
-- Definition of table `regions`
-- 

DROP TABLE IF EXISTS `regions`;
CREATE TABLE `regions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `region` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=latin1;


INSERT INTO `regions` (`id`,`region`) VALUES 
 (1,'Luzon REGION I (Ilocos Region)'),
 (2,'Luzon REGION II (Cagayan Valley)'),
 (3,'Luzon REGION III (Central Luzon)');
INSERT INTO `regions` (`id`,`region`) VALUES 
 (4,'Luzon REGION IV-A (CALABARZON)'),
 (5,'REGION IV-B (MIMAROPA)');
INSERT INTO `regions` (`id`,`region`) VALUES 
 (6,'Luzon REGION V (BICOL Region)'),
 (7,'Luzon REGION V (BICOL Region)'),
 (8,'VISAYAS REGION VI (WESTERN VISAYAS)'),
 (9,'VISAYAS REGION VII (CENTRAL VISAYAS)'),
 (10,'VISAYAS REGION VIII (EASTERN VISAYAS)');
INSERT INTO `regions` (`id`,`region`) VALUES 
 (11,'MINDANAO REGION IX (Zamboanga Peninsula)'),
 (12,'MINDANAO REGION X (Northern Mindanao)'),
 (13,'MINDANAO REGION XI (Davao Region)'),
 (14,'MINDANAO REGION XII (Soccsksargen Region)'),
 (15,'MINDANAO REGION XIII (Caraga Region)');
INSERT INTO `regions` (`id`,`region`) VALUES 
 (16,'LUZON REGION XIV (Cordillera Administrative Region (CAR) Region)');
--
-- Dumping data for table `regions`
--